"""empty message

Revision ID: 735bc7e63011
Revises: a5cffa318ac2
Create Date: 2024-02-14 19:56:46.031627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735bc7e63011'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=False),
    sa.Column('genero', sa.Enum('masculino', 'femenino', name='Genero'), nullable=False),
    sa.Column('hair_color', sa.Enum('negro', 'rubio', name='HairColor'), nullable=False),
    sa.Column('eye_color', sa.Enum('verdes', 'azules', name='EyeColor'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planetId', sa.Integer(), nullable=True),
    sa.Column('characterId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterId'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planetId'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
